name: "Publish slides"

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test it
      run: |
        pwd
        ls -alh

    steps:
      - name: Deploy Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ../slides/
          clean: true
          ssh-key: ${{ secrets.DEPLOY_KEY }}